services:
  # ====================
  # NATS Server
  # ====================
  nats-server:
    image: nats:latest

  # ====================
  #  Gateway
  # ====================
  client-api-gateway:
    image: aguekdjian/client-api-gateway-prod
    depends_on:
      - nats-server
    ports:
      - ${CLIENT_GATEWAY_PORT}:${CLIENT_GATEWAY_PORT}
    environment:
      - PORT=${CLIENT_GATEWAY_PORT}
      - NATS_SERVERS=${NATS_SERVERS}

  # ====================
  # Clients Microservice
  # ====================
  clients-ms:
    image: aguekdjian/clients-ms-prod
    depends_on:
      - nats-server
    environment:
      - PORT=${CLIENT_MS_PORT}
      - NATS_SERVERS=${NATS_SERVERS}
      - MONGO_CLIENT_URL=${MONGO_CLIENT_URL}

  # ====================
  # Auth Microservice
  # ====================
  auth-ms:
    image: aguekdjian/auth-ms-prod
    depends_on:
      - nats-server
    environment:
      - PORT=${AUTH_MS_PORT}
      - NATS_SERVERS=${NATS_SERVERS}
      - MONGO_AUTH_URL=${MONGO_AUTH_URL}
      - JWT_SECRET=${JWT_SECRET}

  # ====================
  # Frontend
  # ====================
  frontend:
    image: aguekdjian/frontend
    depends_on:
      - client-api-gateway
    ports:
      - ${FRONTEND_PORT}:${FRONTEND_PORT}
