services:
  # ====================
  # NATS Server
  # ====================
  nats-server:
    image: nats:latest

  # ====================
  #  Gateway
  # ====================
  client-gateway:
    build:
      context: ./client-api-gateway
      dockerfile: Dockerfile.prod
    image: client-api-gateway-prod
    ports:
      - ${CLIENT_GATEWAY_PORT}:${CLIENT_GATEWAY_PORT}
    environment:
      - PORT=${CLIENT_GATEWAY_PORT}
      - NATS_SERVERS=${NATS_SERVERS}

  # ====================
  # Clients Microservice
  # ====================
  clients-ms:
    build:
      context: ./clients-ms
      dockerfile: Dockerfile.prod
    image: clients-ms-prod
    environment:
      - PORT=${CLIENT_MS_PORT}
      - NATS_SERVERS=${NATS_SERVERS}
      - MONGO_CLIENT_URL=${MONGO_CLIENT_URL}

  # ====================
  # Auth Microservice
  # ====================
  auth-ms:
    build:
      context: ./auth-ms
      dockerfile: Dockerfile.prod
    image: auth-ms-prod
    environment:
      - PORT=${AUTH_MS_PORT}
      - NATS_SERVERS=${NATS_SERVERS}
      - MONGO_AUTH_URL=${MONGO_AUTH_URL}
      - JWT_SECRET=${JWT_SECRET}
