global:
  scrape_interval: 15s

scrape_configs:
  - job_name: "api_gateway"
    static_configs:
      - targets: ["client-api-gateway:8080"]
    metrics_path: /api/metrics

  - job_name: "microservices"
    static_configs:
      - targets: ["clients-ms:3011", "auth-ms:3016", "orders-ms:3021"]

  - job_name: "nats"
    static_configs:
      - targets: ["nats_exporter:7777"]
