name: EC2 Production Deployment

on:
  pull_request:
    branches: [main]

jobs:
  avoid_redundancy:
    runs-on: ubuntu-22.04
    steps:
      - name: Cancel Previous Redundant Deployments
        uses: styfle/cancel-workflow-action@0.12.1
        with:
          access_token: ${{github.token}}

  deploy:
    needs: avoid_redundancy
    runs-on: aws-ec2-mialarma-app
    steps:
      - uses: actions/checkout@v4.1.7
        with:
          fetch-depth: 0
      - name: Stopping and Removing containers
        run: cd
